name: Deploiement sur GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write

    outputs:
      page_url: ${{ steps.artifacts.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Prepare
        run: |
          mkdir ./dist
          cp *.html ./dist
          cp robots.txt ./dist
          cp -rf build ./dist && rm ./dist/build/.gitignore
          cp -rf data ./dist
          cp -rf public ./dist
          cp -rf images ./dist

      - name: Upload static files as artifact
        id: artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ job.build.outputs.page_url }}
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
